-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 15:11:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `Person_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email_address` VARCHAR(45) NOT NULL,
  `Physical_address` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Person_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine_certification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine_certification` (
  `Vaccine_certification_ID` VARCHAR(45) NOT NULL,
  `Dosage` INT NOT NULL,
  `Date_last_dose` DATE NOT NULL,
  PRIMARY KEY (`Vaccine_certification_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `Passport_number` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(45) NOT NULL,
  `Email_address` VARCHAR(45) NOT NULL,
  `Flight_QR_Code` VARCHAR(45) NOT NULL,
  `Vaccine_certification_Vaccine_certification_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Passport_number`, `Vaccine_certification_Vaccine_certification_ID`),
  INDEX `fk_Passenger_Vaccine_certification1_idx` (`Vaccine_certification_Vaccine_certification_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Vaccine_certification1`
    FOREIGN KEY (`Vaccine_certification_Vaccine_certification_ID`)
    REFERENCES `mydb`.`Vaccine_certification` (`Vaccine_certification_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight_Menu` (
  `Menu_ID` INT NOT NULL,
  `Economy_Class_Menu` VARCHAR(45) NOT NULL,
  `Premium_Class_Menu` VARCHAR(45) NOT NULL,
  `Business_Class_Menu` VARCHAR(45) NOT NULL,
  `First_Class_Menu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Menu_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `Airport_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Town` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `International_Code` INT NOT NULL,
  PRIMARY KEY (`Airport_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `International_ID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Origin` VARCHAR(45) NOT NULL,
  `Active_or_not` VARCHAR(3) NOT NULL,
  `Airport_ID` INT NOT NULL,
  PRIMARY KEY (`International_ID`, `Airport_ID`),
  INDEX `fk_Airline_Airport1_idx` (`Airport_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Airline_Airport1`
    FOREIGN KEY (`Airport_ID`)
    REFERENCES `mydb`.`Airport` (`Airport_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft_Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft_Model` (
  `Model_ID` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Seats_Number` INT NOT NULL,
  `Weight` INT NOT NULL,
  PRIMARY KEY (`Model_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `Aircraft_Code` INT NOT NULL,
  `Aircraft_Model` INT NOT NULL,
  `Airline_International_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Aircraft_Code`, `Aircraft_Model`),
  INDEX `fk_Aircraft_Aircraft_Model1_idx` (`Aircraft_Model` ASC) VISIBLE,
  INDEX `fk_Aircraft_Airline1_idx` (`Airline_International_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Aircraft_Aircraft_Model1`
    FOREIGN KEY (`Aircraft_Model`)
    REFERENCES `mydb`.`Aircraft_Model` (`Model_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aircraft_Airline1`
    FOREIGN KEY (`Airline_International_ID`)
    REFERENCES `mydb`.`Airline` (`International_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `Flight_Number` INT NOT NULL,
  `Destination` VARCHAR(45) NOT NULL,
  `Destination_Date` DATETIME NOT NULL,
  `Airport_TakeOff` VARCHAR(45) NOT NULL,
  `TakeOff_Date` DATETIME NOT NULL,
  `Flight_Menu` INT NOT NULL,
  `Airline_International_ID` VARCHAR(45) NOT NULL,
  `Aircraft_Aircraft_Code` INT NOT NULL,
  PRIMARY KEY (`Flight_Number`, `Flight_Menu`),
  INDEX `fk_Flight_Flight_Menu1_idx` (`Flight_Menu` ASC) VISIBLE,
  INDEX `fk_Flight_Airline1_idx` (`Airline_International_ID` ASC) VISIBLE,
  INDEX `fk_Flight_Aircraft1_idx` (`Aircraft_Aircraft_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Flight_Menu1`
    FOREIGN KEY (`Flight_Menu`)
    REFERENCES `mydb`.`Flight_Menu` (`Menu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_International_ID`)
    REFERENCES `mydb`.`Airline` (`International_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Aircraft1`
    FOREIGN KEY (`Aircraft_Aircraft_Code`)
    REFERENCES `mydb`.`Aircraft` (`Aircraft_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation_System`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation_System` (
  `Reservation_ID` INT NOT NULL,
  `Reservation_seat_class` ENUM("ECONOMY", "BUSINESS", "PREMIUM ECONOMY", "FIRST") NOT NULL,
  `Reservation_Date` VARCHAR(45) NOT NULL,
  `Comments` VARCHAR(45) NULL,
  `Passenger_Passport_number` INT NOT NULL,
  `Flight_Flight_Number` INT NOT NULL,
  `Flight_Flight_Menu` INT NOT NULL,
  PRIMARY KEY (`Reservation_ID`, `Passenger_Passport_number`, `Flight_Flight_Number`, `Flight_Flight_Menu`),
  INDEX `fk_Reservation_System_Passenger1_idx` (`Passenger_Passport_number` ASC) VISIBLE,
  INDEX `fk_Reservation_System_Flight1_idx` (`Flight_Flight_Number` ASC, `Flight_Flight_Menu` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_System_Passenger1`
    FOREIGN KEY (`Passenger_Passport_number`)
    REFERENCES `mydb`.`Passenger` (`Passport_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_System_Flight1`
    FOREIGN KEY (`Flight_Flight_Number` , `Flight_Flight_Menu`)
    REFERENCES `mydb`.`Flight` (`Flight_Number` , `Flight_Menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation_Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation_Page` (
  `Reservation_Page_Name` VARCHAR(45) NOT NULL,
  `Reservation_System_Reservation_ID` INT NOT NULL,
  PRIMARY KEY (`Reservation_Page_Name`, `Reservation_System_Reservation_ID`),
  INDEX `fk_Reservation_Page_Reservation_System1_idx` (`Reservation_System_Reservation_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Page_Reservation_System1`
    FOREIGN KEY (`Reservation_System_Reservation_ID`)
    REFERENCES `mydb`.`Reservation_System` (`Reservation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Research` (
  `Research_Title` VARCHAR(45) NOT NULL,
  `Flight_Type` VARCHAR(45) NOT NULL,
  `Departure_date` VARCHAR(45) NOT NULL,
  `General_info` VARCHAR(45) NOT NULL,
  `Reservation_Page_ID` INT NOT NULL,
  INDEX `fk_Research_Reservation_Page1_idx` (`Reservation_Page_ID` ASC) VISIBLE,
  PRIMARY KEY (`Research_Title`),
  CONSTRAINT `fk_Research_Reservation_Page1`
    FOREIGN KEY (`Reservation_Page_ID`)
    REFERENCES `mydb`.`Reservation_Page` (`Reservation_Page_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person_does_Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person_does_Research` (
  `Person_Person_ID` INT NOT NULL,
  `Research_Research_Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Person_Person_ID`, `Research_Research_Title`),
  INDEX `fk_Person_has_Research_Research1_idx` (`Research_Research_Title` ASC) VISIBLE,
  INDEX `fk_Person_has_Research_Person1_idx` (`Person_Person_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Person_has_Research_Person1`
    FOREIGN KEY (`Person_Person_ID`)
    REFERENCES `mydb`.`Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Research_Research1`
    FOREIGN KEY (`Research_Research_Title`)
    REFERENCES `mydb`.`Research` (`Research_Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `ID_number` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Salary` INT NOT NULL,
  `Speciality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician_specifies_in_Aircraft_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician_specifies_in_Aircraft_model` (
  `Technician_id_number` INT NOT NULL,
  `Aircraft_Model_ID` INT NOT NULL,
  PRIMARY KEY (`Technician_id_number`, `Aircraft_Model_ID`),
  INDEX `fk_Technicians_has_Aircraft_Model_Aircraft_Model1_idx` (`Aircraft_Model_ID` ASC) VISIBLE,
  INDEX `fk_Technicians_has_Aircraft_Model_Technicians1_idx` (`Technician_id_number` ASC) VISIBLE,
  CONSTRAINT `fk_Technicians_has_Aircraft_Model_Technicians1`
    FOREIGN KEY (`Technician_id_number`)
    REFERENCES `mydb`.`Technician` (`ID_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technicians_has_Aircraft_Model_Aircraft_Model1`
    FOREIGN KEY (`Aircraft_Model_ID`)
    REFERENCES `mydb`.`Aircraft_Model` (`Model_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Air_Traffic_Controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Air_Traffic_Controller` (
  `ID_number` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Medical_CheckUp` DATE NOT NULL,
  PRIMARY KEY (`ID_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `Union_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Foundation_Date` DATE NOT NULL,
  PRIMARY KEY (`Union_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technicians_Check_Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technicians_Check_Aircraft` (
  `Check_number` INT NOT NULL,
  `Check_Date` DATE NOT NULL,
  `Hours_needed` INT NOT NULL,
  `Technicians_ID_number` INT NOT NULL,
  `Aircraft_Aircraft_Code` INT NOT NULL,
  `Aircraft_Aircraft_Model_Model_ID` INT NOT NULL,
  `Aircraft_Airline_International_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_Technicians_has_Aircraft_Aircraft1_idx` (`Aircraft_Aircraft_Code` ASC, `Aircraft_Aircraft_Model_Model_ID` ASC, `Aircraft_Airline_International_ID` ASC) VISIBLE,
  INDEX `fk_Technicians_has_Aircraft_Technicians1_idx` (`Technicians_ID_number` ASC) VISIBLE,
  PRIMARY KEY (`Check_number`),
  CONSTRAINT `fk_Technicians_has_Aircraft_Technicians1`
    FOREIGN KEY (`Technicians_ID_number`)
    REFERENCES `mydb`.`Technician` (`ID_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technicians_has_Aircraft_Aircraft1`
    FOREIGN KEY (`Aircraft_Aircraft_Code` , `Aircraft_Aircraft_Model_Model_ID`)
    REFERENCES `mydb`.`Aircraft` (`Aircraft_Code` , `Aircraft_Model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`YPA_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`YPA_check` (
  `YPA_check_ID` INT NOT NULL,
  `YPA_Name` VARCHAR(45) NOT NULL,
  `Max score` VARCHAR(45) NOT NULL,
  `Airport_Airport_ID` INT NOT NULL,
  `Technicians_Check_number` INT NOT NULL,
  PRIMARY KEY (`YPA_check_ID`, `Airport_Airport_ID`, `Technicians_Check_number`),
  INDEX `fk_YPA_check_Airport1_idx` (`Airport_Airport_ID` ASC) VISIBLE,
  INDEX `fk_YPA_check_Technicians_Check1_idx` (`Technicians_Check_number` ASC) VISIBLE,
  CONSTRAINT `fk_YPA_check_Airport1`
    FOREIGN KEY (`Airport_Airport_ID`)
    REFERENCES `mydb`.`Airport` (`Airport_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_YPA_check_Technicians_Check1`
    FOREIGN KEY (`Technicians_Check_number`)
    REFERENCES `mydb`.`Technicians_Check_Aircraft` (`Check_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Ticket_ID` INT NOT NULL,
  `QR_code` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Reservation_Page_ID` INT NOT NULL,
  `Reservation_ID` INT NOT NULL,
  `Passenger_Passport_number` INT NOT NULL,
  PRIMARY KEY (`Ticket_ID`, `Reservation_Page_ID`, `Reservation_ID`, `Passenger_Passport_number`),
  INDEX `fk_Ticket_Reservation_Page1_idx` (`Reservation_Page_ID` ASC, `Reservation_ID` ASC) VISIBLE,
  INDEX `fk_Ticket_Passenger1_idx` (`Passenger_Passport_number` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Reservation_Page1`
    FOREIGN KEY (`Reservation_Page_ID` , `Reservation_ID`)
    REFERENCES `mydb`.`Reservation_Page` (`Reservation_Page_Name` , `Reservation_System_Reservation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_Passport_number`)
    REFERENCES `mydb`.`Passenger` (`Passport_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union_Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union_Member` (
  `Technician_ID_number` INT NULL,
  `Air_Traffic_Controller_ID_number` INT NULL,
  `Union_Union_ID` INT NOT NULL,
  INDEX `fk_Union_Member_Technician1_idx` (`Technician_ID_number` ASC) VISIBLE,
  INDEX `fk_Union_Member_Air_Traffic_Controller1_idx` (`Air_Traffic_Controller_ID_number` ASC) VISIBLE,
  INDEX `fk_Union_Member_Union1_idx` (`Union_Union_ID` ASC) VISIBLE,
  PRIMARY KEY (`Union_Union_ID`),
  CONSTRAINT `fk_Union_Member_Technician1`
    FOREIGN KEY (`Technician_ID_number`)
    REFERENCES `mydb`.`Technician` (`ID_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Union_Member_Air_Traffic_Controller1`
    FOREIGN KEY (`Air_Traffic_Controller_ID_number`)
    REFERENCES `mydb`.`Air_Traffic_Controller` (`ID_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Union_Member_Union1`
    FOREIGN KEY (`Union_Union_ID`)
    REFERENCES `mydb`.`Union` (`Union_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manifest_List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manifest_List` (
  `Flight_Flight_Number` INT NOT NULL,
  INDEX `fk_Manifest_List_Flight1_idx` (`Flight_Flight_Number` ASC) VISIBLE,
  PRIMARY KEY (`Flight_Flight_Number`),
  CONSTRAINT `fk_Manifest_List_Flight1`
    FOREIGN KEY (`Flight_Flight_Number`)
    REFERENCES `mydb`.`Flight` (`Flight_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manifest_Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manifest_Reservation` (
  `Flight_Number` INT NOT NULL,
  `Reservation_ID` INT NOT NULL,
  `Passenger_Passport_number` INT NOT NULL,
  PRIMARY KEY (`Flight_Number`),
  INDEX `fk_Manifest_passenger_Reservation_System1_idx` (`Reservation_ID` ASC, `Passenger_Passport_number` ASC) VISIBLE,
  CONSTRAINT `fk_Manifest_passenger_Manifest_List1`
    FOREIGN KEY (`Flight_Number`)
    REFERENCES `mydb`.`Manifest_List` (`Flight_Flight_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manifest_passenger_Reservation_System1`
    FOREIGN KEY (`Reservation_ID` , `Passenger_Passport_number`)
    REFERENCES `mydb`.`Reservation_System` (`Reservation_ID` , `Passenger_Passport_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
